author: Nimari
name: PermissionEffectsRedux
main: nimari.tk.Main
description: Spigot plugin that gives players Potion Effects based on permission.
commands:
  permissioneffects:
    aliases: [pe]
    permission: pe.admin