author: Nimari
name: PermissionEffectsRedux
main: tk.nimari.Main
api-version: 1.14
version: 1.3
description: Spigot plugin that gives players Potion Effects based on permission.
commands:
  permissioneffects:
    aliases: [pe]
    permission: pe.admin